# Generated by Django 3.2.9 on 2021-11-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name fruit')),
                ('number', models.PositiveIntegerField(default=0, verbose_name='number fruit present')),
            ],
        ),
    ]
